### ISSUE TITLE
sasl authentication .

### ISSUE THREAD

**Issue by joshypj** [provectus/kafka-ui-charts#23]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/provectus/kafka-ui/issues) and [here](https://github.com/provectus/kafka-ui-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

how to provide the sasl protocol and authentication at values.yaml file at helm chart level.?

yamlApplicationConfig:
  {}
  # kafka:
  #   clusters:
  #     - name: yaml
  #       bootstrapServers: kafka-service:9092
  # spring:
  #   security:
  #     oauth2:
  # auth:
  #   type: disabled
  # management:
  #   health:
  #     ldap:
  #       enabled: false
  

getting below error while trying to connect with a kafka cluster which uses sasl authentication 

[2023-12-08 08:51:40,401] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56258-290) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)

### Expected behavior

tor)
[2023-12-08 08:51:40,401] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56258-290) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
[2023-12-08 08:51:41,206] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56274-290) (Unexpected Kafka request of type METADATA during SASL handshake.) 

### Your installation details

option to accept ..
                         sasl_mechanism='PLAIN',
                         security_protocol='SASL_PLAINTEXT',
                         sasl_plain_username='username',
                         sasl_plain_password='password',

### Steps to reproduce

used the latest kafka-ui helm chart

### Screenshots

[2023-12-08 08:51:40,401] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56258-290) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
[2023-12-08 08:51:41,206] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56274-290) (Unexpected Kafka request of type METADATA during SASL handshake.) 

### Logs

[2023-12-08 08:51:40,401] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56258-290) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
[2023-12-08 08:51:41,206] INFO [SocketServer listenerType=BROKER, nodeId=2] Failed authentication with /10.224.1.121 (channelId=10.224.1.221:9092-10.224.1.121:56274-290) (Unexpected Kafka request of type METADATA during SASL handshake.) 

### Additional context

connecting to existing kafka with sasl authentication

**Comment by angeloimm** [comment]
this is how I wrote my values.yaml:

```
   kafka:
     clusters:
       - name: "MyBrokerName"
         bootstrapServers: my_broker_url:9092
         properties:
           security.protocol: "SASL_PLAINTEXT"
           sasl.mechanism: "SCRAM-SHA-256"        
           sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\u0022MY_BROKER_USERNAME\u0022 password=\u0022MY_BROKER_PWD\u0022;"
```
