### ISSUE TITLE
[Feature] Support OCI artifacts for Helm chart

### ISSUE THREAD

**Issue by patsevanton** [provectus/kafka-ui-charts#39]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/provectus/kafka-ui/issues) and [here](https://github.com/provectus/kafka-ui-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I have helm chart and subcharts. When i try add kafka-ui to subchart:
```
apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 25.10.0
appVersion: 24.7.1
dependencies:
  - name: kafka-ui
    repository: https://provectus.github.io/kafka-ui-charts
    version: 0.7.6
    condition: kafka-ui.enabled
```

i get [error](https://github.com/sentry-kubernetes/charts/pull/1479):
```
Error: no repository definition for https://provectus.github.io/kafka-ui-charts. Please add the missing repos via 'helm repo add'
```

Please consider using the OCI repository to publish helm charts. 

Advantages of using OCI repositories for helm charts:
- With OCI based Helm Charts, you get the familiar command syntax as with interacting with container images runtimes. registry login
- Fewer commands needed for installing Charts. No repo add and repo update commands anymore.
- Publishing Helm Charts to OCI registries does not need the separate plugin cm-push plugin anymore.
- The performance for repositories with many Helm Charts is better.

### Expected behavior

No repo add and repo update commands anymore.

### Your installation details

-

### Steps to reproduce

-
